openapi: 3.1.0
info:
  title: Star Wars API
  description: An API inspired by the Star Wars universe
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /jedi:
    get:
      summary: Jedi endpoint
      description: Returns a message from a Jedi
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: May the Force be with you!
  /sith:
    get:
      summary: Sith endpoint
      description: Returns a message from a Sith
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: I am your father!
