/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vgd.openapi.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

/**
 * ApiErrorUnauthorized - Unauthorized error
 */
@SuppressWarnings("serial")
public class ApiErrorUnauthorized extends RuntimeException {

    @JsonProperty("status")
    private int status;

    @JsonProperty("error")
    private String error;

    @JsonCreator
    public ApiErrorUnauthorized(
            @JsonProperty("status") int status,
            @JsonProperty("error") String error) {
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(error, "error");
        this.status = status;
        this.error = error;
    }

    public int status(){
        return status;
    }

    public String error(){
        return error;
    }
    
    public final static Builder builder() {
        return new Builder();
    }

    public ApiErrorUnauthorized withStatus(int status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    public ApiErrorUnauthorized withError(String error) {
        Utils.checkNotNull(error, "error");
        this.error = error;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApiErrorUnauthorized other = (ApiErrorUnauthorized) o;
        return
            Objects.deepEquals(this.status, other.status) &&
            Objects.deepEquals(this.error, other.error);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            status,
            error);
    }

    @Override
    public String toString() {
        return Utils.toString(ApiErrorUnauthorized.class,
                "status", status,
                "error", error);
    }

    public final static class Builder {

        private Integer status;

        private String error;

        private Builder() {
          // force use of static builder() method
        }

        public Builder status(int status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }

        public Builder error(String error) {
            Utils.checkNotNull(error, "error");
            this.error = error;
            return this;
        }

        public ApiErrorUnauthorized build() {
            return new ApiErrorUnauthorized(
                status,
                error);
        }
    }
}
