/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * OrderStatus - Order Status
 */
public enum OrderStatus {
    PLACED("placed"),
    APPROVED("approved"),
    DELIVERED("delivered");

    @JsonValue
    private final String value;

    private OrderStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
