/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.vishalg0wda.deathstar.models.operations;


public class GetJediRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetJedi sdk;

    public GetJediRequestBuilder(SDKMethodInterfaces.MethodCallGetJedi sdk) {
        this.sdk = sdk;
    }

    public GetJediResponse call() throws Exception {

        return sdk.getDirect();
    }
}
