/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.vishalg0wda.deathstar.models.operations;


public class GetSithRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetSith sdk;

    public GetSithRequestBuilder(SDKMethodInterfaces.MethodCallGetSith sdk) {
        this.sdk = sdk;
    }

    public GetSithResponse call() throws Exception {

        return sdk.getDirect();
    }
}
