/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.vishalg0wda.deathstar.models.operations;

import java.lang.Exception;

public class SDKMethodInterfaces {


    public interface MethodCallGetJedi {
        GetJediResponse getDirect() throws Exception;
    }


    public interface MethodCallGetSith {
        GetSithResponse getDirect() throws Exception;
    }


}
