/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.models.components.Pet;
import com.vgd.openapi.utils.Utils;

public class AddPetRequestBuilder {

    private Pet request;
    private final SDKMethodInterfaces.MethodCallAddPet sdk;

    public AddPetRequestBuilder(SDKMethodInterfaces.MethodCallAddPet sdk) {
        this.sdk = sdk;
    }

    public AddPetRequestBuilder request(Pet request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public AddPetResponse call() throws Exception {

        return sdk.add(
            request);
    }
}
