/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.models.components.User;
import com.vgd.openapi.utils.Utils;
import java.util.List;
import java.util.Optional;

public class CreateUsersWithListInputRequestBuilder {

    private Optional<? extends List<User>> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallCreateUsersWithListInput sdk;

    public CreateUsersWithListInputRequestBuilder(SDKMethodInterfaces.MethodCallCreateUsersWithListInput sdk) {
        this.sdk = sdk;
    }
                
    public CreateUsersWithListInputRequestBuilder request(List<User> request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public CreateUsersWithListInputRequestBuilder request(Optional<? extends List<User>> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateUsersWithListInputResponse call() throws Exception {

        return sdk.createWithList(
            request);
    }
}
