/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.String;

public class DeleteUserRequestBuilder {

    private String username;
    private final SDKMethodInterfaces.MethodCallDeleteUser sdk;

    public DeleteUserRequestBuilder(SDKMethodInterfaces.MethodCallDeleteUser sdk) {
        this.sdk = sdk;
    }

    public DeleteUserRequestBuilder username(String username) {
        Utils.checkNotNull(username, "username");
        this.username = username;
        return this;
    }

    public DeleteUserResponse call() throws Exception {

        return sdk.delete(
            username);
    }
}
