/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.Long;

public class DeleteOrderRequestBuilder {

    private Long orderId;
    private final SDKMethodInterfaces.MethodCallDeleteOrder sdk;

    public DeleteOrderRequestBuilder(SDKMethodInterfaces.MethodCallDeleteOrder sdk) {
        this.sdk = sdk;
    }

    public DeleteOrderRequestBuilder orderId(long orderId) {
        Utils.checkNotNull(orderId, "orderId");
        this.orderId = orderId;
        return this;
    }

    public DeleteOrderResponse call() throws Exception {

        return sdk.deleteOrder(
            orderId);
    }
}
