/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

public class DeletePetRequestBuilder {

    private Optional<String> apiKey = Optional.empty();
    private Long petId;
    private final SDKMethodInterfaces.MethodCallDeletePet sdk;

    public DeletePetRequestBuilder(SDKMethodInterfaces.MethodCallDeletePet sdk) {
        this.sdk = sdk;
    }
                
    public DeletePetRequestBuilder apiKey(String apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = Optional.of(apiKey);
        return this;
    }

    public DeletePetRequestBuilder apiKey(Optional<String> apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = apiKey;
        return this;
    }

    public DeletePetRequestBuilder petId(long petId) {
        Utils.checkNotNull(petId, "petId");
        this.petId = petId;
        return this;
    }

    public DeletePetResponse call() throws Exception {

        return sdk.delete(
            apiKey,
            petId);
    }
}
