/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public class FindPetsByTagsRequestBuilder {

    private Optional<? extends List<String>> tags = Optional.empty();
    private final SDKMethodInterfaces.MethodCallFindPetsByTags sdk;

    public FindPetsByTagsRequestBuilder(SDKMethodInterfaces.MethodCallFindPetsByTags sdk) {
        this.sdk = sdk;
    }
                
    public FindPetsByTagsRequestBuilder tags(List<String> tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = Optional.of(tags);
        return this;
    }

    public FindPetsByTagsRequestBuilder tags(Optional<? extends List<String>> tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = tags;
        return this;
    }

    public FindPetsByTagsResponse call() throws Exception {

        return sdk.findByTags(
            tags);
    }
}
