/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.vgd.openapi.utils.LazySingletonValue;
import com.vgd.openapi.utils.Utils;
import java.util.Optional;

public class FindPetsByStatusRequestBuilder {

    private Optional<? extends Status> status = Utils.readDefaultOrConstValue(
                            "status",
                            "\"available\"",
                            new TypeReference<Optional<? extends Status>>() {});
    private final SDKMethodInterfaces.MethodCallFindPetsByStatus sdk;

    public FindPetsByStatusRequestBuilder(SDKMethodInterfaces.MethodCallFindPetsByStatus sdk) {
        this.sdk = sdk;
    }
                
    public FindPetsByStatusRequestBuilder status(Status status) {
        Utils.checkNotNull(status, "status");
        this.status = Optional.of(status);
        return this;
    }

    public FindPetsByStatusRequestBuilder status(Optional<? extends Status> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    public FindPetsByStatusResponse call() throws Exception {
        if (status == null) {
            status = _SINGLETON_VALUE_Status.value();
        }
        return sdk.findByStatus(
            status);
    }

    private static final LazySingletonValue<Optional<? extends Status>> _SINGLETON_VALUE_Status =
            new LazySingletonValue<>(
                    "status",
                    "\"available\"",
                    new TypeReference<Optional<? extends Status>>() {});
}
