/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vgd.openapi.utils.SpeakeasyMetadata;
import com.vgd.openapi.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;


public class GetPetByIdRequest {

    /**
     * ID of pet to return
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")
    private long petId;

    @JsonCreator
    public GetPetByIdRequest(
            long petId) {
        Utils.checkNotNull(petId, "petId");
        this.petId = petId;
    }

    /**
     * ID of pet to return
     */
    @JsonIgnore
    public long petId() {
        return petId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * ID of pet to return
     */
    public GetPetByIdRequest withPetId(long petId) {
        Utils.checkNotNull(petId, "petId");
        this.petId = petId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPetByIdRequest other = (GetPetByIdRequest) o;
        return 
            Objects.deepEquals(this.petId, other.petId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            petId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPetByIdRequest.class,
                "petId", petId);
    }
    
    public final static class Builder {
 
        private Long petId;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of pet to return
         */
        public Builder petId(long petId) {
            Utils.checkNotNull(petId, "petId");
            this.petId = petId;
            return this;
        }
        
        public GetPetByIdRequest build() {
            return new GetPetByIdRequest(
                petId);
        }
    }
}

