/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.String;

public class GetUserByNameRequestBuilder {

    private String username;
    private final SDKMethodInterfaces.MethodCallGetUserByName sdk;

    public GetUserByNameRequestBuilder(SDKMethodInterfaces.MethodCallGetUserByName sdk) {
        this.sdk = sdk;
    }

    public GetUserByNameRequestBuilder username(String username) {
        Utils.checkNotNull(username, "username");
        this.username = username;
        return this;
    }

    public GetUserByNameResponse call() throws Exception {

        return sdk.getByName(
            username);
    }
}
