/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class LoginUserRequestBuilder {

    private Optional<String> username = Optional.empty();
    private Optional<String> password = Optional.empty();
    private final SDKMethodInterfaces.MethodCallLoginUser sdk;

    public LoginUserRequestBuilder(SDKMethodInterfaces.MethodCallLoginUser sdk) {
        this.sdk = sdk;
    }
                
    public LoginUserRequestBuilder username(String username) {
        Utils.checkNotNull(username, "username");
        this.username = Optional.of(username);
        return this;
    }

    public LoginUserRequestBuilder username(Optional<String> username) {
        Utils.checkNotNull(username, "username");
        this.username = username;
        return this;
    }
                
    public LoginUserRequestBuilder password(String password) {
        Utils.checkNotNull(password, "password");
        this.password = Optional.of(password);
        return this;
    }

    public LoginUserRequestBuilder password(Optional<String> password) {
        Utils.checkNotNull(password, "password");
        this.password = password;
        return this;
    }

    public LoginUserResponse call() throws Exception {

        return sdk.login(
            username,
            password);
    }
}
