/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vgd.openapi.utils.SpeakeasyMetadata;
import com.vgd.openapi.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;


public class LoginUserRequest {

    /**
     * The user name for login
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=username")
    private Optional<String> username;

    /**
     * The password for login in clear text
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=password")
    private Optional<String> password;

    @JsonCreator
    public LoginUserRequest(
            Optional<String> username,
            Optional<String> password) {
        Utils.checkNotNull(username, "username");
        Utils.checkNotNull(password, "password");
        this.username = username;
        this.password = password;
    }
    
    public LoginUserRequest() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * The user name for login
     */
    @JsonIgnore
    public Optional<String> username() {
        return username;
    }

    /**
     * The password for login in clear text
     */
    @JsonIgnore
    public Optional<String> password() {
        return password;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The user name for login
     */
    public LoginUserRequest withUsername(String username) {
        Utils.checkNotNull(username, "username");
        this.username = Optional.ofNullable(username);
        return this;
    }

    /**
     * The user name for login
     */
    public LoginUserRequest withUsername(Optional<String> username) {
        Utils.checkNotNull(username, "username");
        this.username = username;
        return this;
    }

    /**
     * The password for login in clear text
     */
    public LoginUserRequest withPassword(String password) {
        Utils.checkNotNull(password, "password");
        this.password = Optional.ofNullable(password);
        return this;
    }

    /**
     * The password for login in clear text
     */
    public LoginUserRequest withPassword(Optional<String> password) {
        Utils.checkNotNull(password, "password");
        this.password = password;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LoginUserRequest other = (LoginUserRequest) o;
        return 
            Objects.deepEquals(this.username, other.username) &&
            Objects.deepEquals(this.password, other.password);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            username,
            password);
    }
    
    @Override
    public String toString() {
        return Utils.toString(LoginUserRequest.class,
                "username", username,
                "password", password);
    }
    
    public final static class Builder {
 
        private Optional<String> username = Optional.empty();
 
        private Optional<String> password = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The user name for login
         */
        public Builder username(String username) {
            Utils.checkNotNull(username, "username");
            this.username = Optional.ofNullable(username);
            return this;
        }

        /**
         * The user name for login
         */
        public Builder username(Optional<String> username) {
            Utils.checkNotNull(username, "username");
            this.username = username;
            return this;
        }

        /**
         * The password for login in clear text
         */
        public Builder password(String password) {
            Utils.checkNotNull(password, "password");
            this.password = Optional.ofNullable(password);
            return this;
        }

        /**
         * The password for login in clear text
         */
        public Builder password(Optional<String> password) {
            Utils.checkNotNull(password, "password");
            this.password = password;
            return this;
        }
        
        public LoginUserRequest build() {
            return new LoginUserRequest(
                username,
                password);
        }
    }
}

