/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;


public class LogoutUserRequestBuilder {

    private final SDKMethodInterfaces.MethodCallLogoutUser sdk;

    public LogoutUserRequestBuilder(SDKMethodInterfaces.MethodCallLogoutUser sdk) {
        this.sdk = sdk;
    }

    public LogoutUserResponse call() throws Exception {

        return sdk.logoutDirect();
    }
}
