/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.models.components.Order;
import com.vgd.openapi.utils.Utils;
import java.util.Optional;

public class PlaceOrderRequestBuilder {

    private Optional<? extends Order> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPlaceOrder sdk;

    public PlaceOrderRequestBuilder(SDKMethodInterfaces.MethodCallPlaceOrder sdk) {
        this.sdk = sdk;
    }
                
    public PlaceOrderRequestBuilder request(Order request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public PlaceOrderRequestBuilder request(Optional<? extends Order> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PlaceOrderResponse call() throws Exception {

        return sdk.placeOrder(
            request);
    }
}
