/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.models.components.Pet;
import com.vgd.openapi.utils.Utils;

public class UpdatePetRequestBuilder {

    private Pet request;
    private final SDKMethodInterfaces.MethodCallUpdatePet sdk;

    public UpdatePetRequestBuilder(SDKMethodInterfaces.MethodCallUpdatePet sdk) {
        this.sdk = sdk;
    }

    public UpdatePetRequestBuilder request(Pet request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UpdatePetResponse call() throws Exception {

        return sdk.update(
            request);
    }
}
