/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vgd.openapi.models.operations;

import com.vgd.openapi.utils.Utils;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

public class UploadFileRequestBuilder {

    private Long petId;
    private Optional<String> additionalMetadata = Optional.empty();
    private Optional<? extends byte[]> requestBody = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUploadFile sdk;

    public UploadFileRequestBuilder(SDKMethodInterfaces.MethodCallUploadFile sdk) {
        this.sdk = sdk;
    }

    public UploadFileRequestBuilder petId(long petId) {
        Utils.checkNotNull(petId, "petId");
        this.petId = petId;
        return this;
    }
                
    public UploadFileRequestBuilder additionalMetadata(String additionalMetadata) {
        Utils.checkNotNull(additionalMetadata, "additionalMetadata");
        this.additionalMetadata = Optional.of(additionalMetadata);
        return this;
    }

    public UploadFileRequestBuilder additionalMetadata(Optional<String> additionalMetadata) {
        Utils.checkNotNull(additionalMetadata, "additionalMetadata");
        this.additionalMetadata = additionalMetadata;
        return this;
    }
                
    public UploadFileRequestBuilder requestBody(byte[] requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.of(requestBody);
        return this;
    }

    public UploadFileRequestBuilder requestBody(Optional<? extends byte[]> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public UploadFileResponse call() throws Exception {

        return sdk.uploadFile(
            petId,
            additionalMetadata,
            requestBody);
    }
}
