/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.vishalg0wda.deathstar.models.components;

public class Security {
    // Security not configured but we create this class 
    // to help with SecuritySource references in sdk hook context
}